tracking_service:
    path: /con4gis/api/trackingService/
    defaults:
        _scope: frontend
        _controller: "con4gisTrackingBundle:Tracking:tracking"
    methods: [GET]

tracking_legacy_service:
    path: /system/modules/con4gis_core/api/index.php/trackingService
    defaults:
        _scope: frontend
        _controller: "con4gisTrackingBundle:Tracking:tracking"
    methods: [GET, POST]
  
