tracking_service:
    path: /system/modules/con4gis_core/api/index.php/trackingService
    defaults:
        _scope: frontend
        _controller: "con4gisTrackingBundle:Tracking:tracking"
    methods: [GET]