tracking_service:
    path: /con4gis/api/trackingService
    defaults:
        _scope: frontend
        _controller: con4gis\TrackingBundle\Controller\TrackingController::trackingAction
    methods: [GET, POST]

tracking_service_new_position:
    path: /con4gis/api/trackingService/newPositionFromBox
    defaults:
        _scope: frontend
        _controller: con4gis\TrackingBundle\Controller\TrackingController::trackingActionNewPositionFromBox
    methods: [GET, POST]

tracking_service_getLive:
    path: /con4gis/api/trackingService/getLive/
    defaults:
        _scope: frontend
        _controller: con4gis\TrackingBundle\Controller\TrackingController::getLiveAction
    methods: [GET]

tracking_legacy_service:
    path: /system/modules/con4gis_core/api/index.php/trackingService
    defaults:
        _scope: frontend
        _controller: con4gis\TrackingBundle\Controller\TrackingController::trackingLegacyAction
    methods: [GET, POST]
  
